//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_MvvMTest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AG_AgreementUser
    {
        public int ID_AgreementUser { get; set; }
        public int ID_AgreementClass { get; set; }
        public string MC_AgreementUser { get; set; }
        public string Linkman_AgreementUser { get; set; }
        public string Phone_AgreementUser { get; set; }
        public decimal Price_Balance { get; set; }
        public decimal Prcie_Overdraft { get; set; }
        public Nullable<System.DateTime> Date_Credit { get; set; }
    }
}
