//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_MvvMTest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CW_Bill
    {
        public int ID_Bill { get; set; }
        public int SuOp_ID { get; set; }
        public Nullable<System.DateTime> Time_PayBill { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string State_Bill { get; set; }
        public string Number_Bill { get; set; }
    }
}
