//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_MvvMTest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CW_ConsumeDetail
    {
        public int ID_ComsumeDetail { get; set; }
        public Nullable<int> ID_Project { get; set; }
        public Nullable<int> ID_Consumption { get; set; }
        public Nullable<bool> State_ComsumeDetail { get; set; }
        public Nullable<int> ID_PayRecord { get; set; }
        public Nullable<bool> presenter { get; set; }
        public Nullable<decimal> money { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    }
}
