//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_MvvMTest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CW_Consumption
    {
        public int ID_Consumption { get; set; }
        public int ID_ProjectDetail { get; set; }
        public int ID_RoomStage { get; set; }
        public int ID_Bill { get; set; }
        public int Quantity { get; set; }
        public decimal Prict { get; set; }
        public decimal Discount { get; set; }
        public System.DateTime Time_Consumption { get; set; }
    }
}
