//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_MvvMTest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CW_Finance
    {
        public int ID_Finance { get; set; }
        public int ID_User { get; set; }
        public int Use_ID_User { get; set; }
        public decimal Alipay { get; set; }
        public decimal WeChat { get; set; }
        public decimal RMB { get; set; }
        public decimal Curtain { get; set; }
        public decimal CreditCard { get; set; }
        public decimal Checks { get; set; }
        public decimal Surplus { get; set; }
        public decimal Income { get; set; }
        public decimal CashPledge { get; set; }
        public decimal Handin { get; set; }
        public decimal Issue { get; set; }
        public decimal Connect { get; set; }
        public string Remark { get; set; }
    }
}
