//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_MvvMTest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CW_PayRecord
    {
        public int ID_PayRecord { get; set; }
        public Nullable<int> ID_Bill { get; set; }
        public Nullable<int> ID_Guest { get; set; }
        public Nullable<decimal> Price_Pay { get; set; }
        public Nullable<decimal> Time_Pay { get; set; }
        public string PoP { get; set; }
        public Nullable<bool> State { get; set; }
    }
}
