//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_MvvMTest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LostAndFound
    {
        public int ID_LostAndFound { get; set; }
        public int ID_RoomStage { get; set; }
        public string C_Content { get; set; }
        public string People_Up { get; set; }
        public System.DateTime Time_Up { get; set; }
        public string Pepple_Claim { get; set; }
        public System.DateTime Time_Claim { get; set; }
        public bool State { get; set; }
    }
}
