//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_MvvMTest.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EasternStar_WPF_MVVMEntities : DbContext
    {
        public EasternStar_WPF_MVVMEntities()
            : base("name=EasternStar_WPF_MVVMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AG_AgreementClass> AG_AgreementClass { get; set; }
        public virtual DbSet<AG_AgreementStagePrice> AG_AgreementStagePrice { get; set; }
        public virtual DbSet<AG_AgreementUser> AG_AgreementUser { get; set; }
        public virtual DbSet<CW_Bill> CW_Bill { get; set; }
        public virtual DbSet<CW_Consumption> CW_Consumption { get; set; }
        public virtual DbSet<CW_Finance> CW_Finance { get; set; }
        public virtual DbSet<CW_PayRecord> CW_PayRecord { get; set; }
        public virtual DbSet<LostAndFound> LostAndFound { get; set; }
        public virtual DbSet<PJ_Project> PJ_Project { get; set; }
        public virtual DbSet<PJ_ProjectClass> PJ_ProjectClass { get; set; }
        public virtual DbSet<PJ_ProjectDetail> PJ_ProjectDetail { get; set; }
        public virtual DbSet<SYS_Class> SYS_Class { get; set; }
        public virtual DbSet<SYS_Guest> SYS_Guest { get; set; }
        public virtual DbSet<SYS_RoomStage> SYS_RoomStage { get; set; }
        public virtual DbSet<SYS_System> SYS_System { get; set; }
        public virtual DbSet<User_Jurisdiction> User_Jurisdiction { get; set; }
        public virtual DbSet<User_OperationLog> User_OperationLog { get; set; }
        public virtual DbSet<User_Table> User_Table { get; set; }
        public virtual DbSet<VIP_Grade> VIP_Grade { get; set; }
        public virtual DbSet<VIP_Table> VIP_Table { get; set; }
        public virtual DbSet<YW_Subscribe> YW_Subscribe { get; set; }
        public virtual DbSet<YW_OpenStage> YW_OpenStage { get; set; }
        public virtual DbSet<CW_ConsumeDetail> CW_ConsumeDetail { get; set; }
    }
}
