//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_MvvMTest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PJ_ProjectDetail
    {
        public decimal ID_ProjectDetail { get; set; }
        public int ID_Class { get; set; }
        public int ID_Project { get; set; }
        public decimal Price { get; set; }
    }
}
