//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_MvvMTest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_RoomStage
    {
        public int ID_RoomStage { get; set; }
        public Nullable<int> ID_Guest { get; set; }
        public int ID_Class { get; set; }
        public string Number_RoomStage { get; set; }
        public string MC_RoomStage { get; set; }
        public string State_RoomStage { get; set; }
        public string Describe { get; set; }
        public int JionSign { get; set; }
    }
}
