//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_MvvMTest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Room_status_type
    {
        public int ID_room_status_type { get; set; }
        public string name_room_status_type { get; set; }
    }
}
