//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_MvvMTest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Class
    {
        public int ID_Class { get; set; }
        public string Code_Class { get; set; }
        public string MC_Class { get; set; }
        public string Jc_Class { get; set; }
        public decimal Price_Plate { get; set; }
        public decimal Price_Actual { get; set; }
        public string Remark { get; set; }
        public string State_Class { get; set; }
    }
}
