//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_MvvMTest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIP_Table
    {
        public int ID_VIP { get; set; }
        public int ID_Guest { get; set; }
        public int ID_Grade { get; set; }
        public decimal Integra_VIPl { get; set; }
        public decimal Price_Balance { get; set; }
        public decimal Prcie_Overdraft { get; set; }
        public System.DateTime Date_Credit { get; set; }
        public string Accounts { get; set; }
    }
}
