//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_MvvMTest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class YW_Subscribe
    {
        public int ID_Subscribe { get; set; }
        public int ID_VIP { get; set; }
        public int ID_AgreementUser { get; set; }
        public int ID_Guest { get; set; }
        public string Number_Subscribe { get; set; }
        public string HouseStageID { get; set; }
        public Nullable<System.DateTime> Time_Predict { get; set; }
        public Nullable<System.DateTime> Time_Leave { get; set; }
        public int Number_People { get; set; }
        public decimal Money_Pledge { get; set; }
        public bool State_Secrecy { get; set; }
        public string Remark { get; set; }
        public string Type_CheckIn { get; set; }
        public string Number_OpenStage { get; set; }
    }
}
